---
title: "CITEseq analysis"
author: "Michael Gildea"
date: "12/21/2022"
output:
  html_document:
    code_folding: hide
    toc: yes
    theme: spacelab
---


```{r, message=F, warning=F}
library(Seurat)
library(ggplot2)
library(ggbeeswarm)
```

#load data
```{r, warning=F, message=F}
#read in data matrices
seurat.data <- Read10X(data.dir = '/gpfs/data/giannarellilab/Mike_G/Immune_checkpoint_inhibitors/PBMC_ICI_CITEseq/count-Plate1-24h/outs/filtered_feature_bc_matrix')
#extract hashtag counts from ADT assay


# we save the 3 tables (sequences, antibody proteins, hashtags) as a seurat object
#extract hashtag counts from ADT assay
hash_counts <- seurat.data$`Antibody Capture`[grep(row.names(seurat.data$`Antibody Capture`), pattern = 'CMO'),]
#remove hashtag counts from ADT assay
seurat.data$`Antibody Capture` <- seurat.data$`Antibody Capture`[-grep(row.names(seurat.data$`Antibody Capture`), pattern = 'CMO'),]
#Add hashtag matrix to list
seurat.data[["HTO"]] <- hash_counts

seurat_24h <- CreateSeuratObject(counts = seurat.data$HTO, assay = "HTO")
seurat_24h[["RNA"]] <- CreateAssayObject(counts = seurat.data$`Gene Expression`)
seurat_24h[["Antibody capture"]] <- CreateAssayObject(counts = seurat.data$`Antibody Capture`)

```

# Sample demultiplexing
## Hasthtag QC
```{r, warning=F, message=F}
# Normalize HTO data, here we use centered log-ratio (CLR) transformation
seurat_24h <- NormalizeData(seurat_24h, assay = "HTO", normalization.method = "CLR")
seurat_24h <- HTODemux(seurat_24h, assay = "HTO", positive.quantile = 0.99)
table(seurat_24h$HTO_classification.global)
table(seurat_24h$HTO_maxID)
Idents(seurat_24h) <- "HTO_classification.global"
VlnPlot(seurat_24h, features = "nCount_RNA", pt.size = 0.1, log = TRUE)
HTOHeatmap(seurat_24h, assay = "HTO")
```

```{r, fig.height=12, fig.width=8, warning=F, message=F}
Idents(seurat_24h) <- "HTO_maxID"
RidgePlot(seurat_24h, assay = "HTO", features = rownames(seurat_24h[["HTO"]]), ncol = 2)
```

## Extract singlets
```{r}
Idents(seurat_24h) <- 'HTO_classification.global'
singlet_24h <- subset(seurat_24h, idents = "Singlet")

sample_id <- as.vector(singlet_24h$orig.ident)
sample_id[which(singlet_24h$hash.ID == 'CMO303')] <- "condition_1" 
sample_id[which(singlet_24h$hash.ID == 'CMO304')] <- "PD1-24h"
sample_id[which(singlet_24h$hash.ID == 'CMO305')] <- "condition_2" 
sample_id[which(singlet_24h$hash.ID == 'CMO306')] <- "PBMC-1-24h"
sample_id[which(singlet_24h$hash.ID == 'CMO307')] <- "condition_3"
sample_id[which(singlet_24h$hash.ID == 'CMO308')] <- "condition_4"
sample_id[which(singlet_24h$hash.ID == 'CMO309')] <- "condition_5"
sample_id[which(singlet_24h$hash.ID == 'CMO310')] <- "condition_6"
sample_id[which(singlet_24h$hash.ID == 'CMO311')] <- "CTLA4-24h" 
sample_id[which(singlet_24h$hash.ID == 'CMO312')] <- "condition_7" 
 
singlet_24h$sample_id <- sample_id
table(singlet_24h$hash.ID, singlet_24h$sample_id)
```

## Split data by sample
```{r, warning = F, message = F}
singlet_24h_list <- SplitObject(singlet_24h, split.by = 'hash.ID')
```

## Assign sample names
```{r, warning = F, message = F}
names(singlet_24h_list)
names(singlet_24h_list)[1] <- 'CTLA4_4h'
names(singlet_24h_list)[2] <- 'condition_1'
names(singlet_24h_list)[3] <- 'condition_2'
names(singlet_24h_list)[4] <- 'PD1_4h'
names(singlet_24h_list)[5] <- 'condition_3'
names(singlet_24h_list)[6] <- 'condition_4'
names(singlet_24h_list)[7] <- 'condition_5'
names(singlet_24h_list)[8] <- 'condition_6'
names(singlet_24h_list)[9] <- 'condition_7'
names(singlet_24h_list)[10] <- 'PBMC-1_4h'
names(singlet_24h_list)
```

# Sample QC
## Total
```{r}
singlet_24h[["percent.mt"]] <- PercentageFeatureSet(singlet_24h, pattern = "^MT-", assay = 'RNA')

ggplot(singlet_24h@meta.data, aes(x = sample_id, y = log10(nFeature_RNA), fill = sample_id))+
  geom_violin()+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 315, hjust = 0))

ggplot(singlet_24h@meta.data, aes(x = sample_id, y = log10(nCount_RNA), fill = sample_id))+
  geom_violin()+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 315, hjust = 0))

ggplot(singlet_24h@meta.data, aes(x = sample_id, y = log10(percent.mt), fill = sample_id))+
  geom_violin()+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 315, hjust = 0))
          
```

## condition_1
```{r, warning = F, message = F}
singlet_24h_list[[1]]
singlet_24h_list[[1]][["percent.mt"]] <- PercentageFeatureSet(singlet_24h_list[[1]], pattern = "^MT-", assay = 'RNA')
VlnPlot(singlet_24h_list[[1]], features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, log = T, pt.size = .5)
VlnPlot(singlet_24h_list[[1]], features = c("nFeature_Antibody.capture", "nCount_Antibody.capture"), ncol = 2, log = T, pt.size = .5, assay = 'Antibody.capture')
qplot(log10(singlet_24h_list[[1]]@meta.data$nCount_RNA), singlet_24h_list[[1]]@meta.data$percent.mt)+
  geom_point(color = 'steelblue')+
  theme_classic()
qplot(log10(singlet_24h_list[[1]]@meta.data$nFeature_RNA), singlet_24h_list[[1]]@meta.data$percent.mt)+
  geom_point(color = 'steelblue')+
  theme_classic()
qplot(log10(singlet_24h_list[[1]]@meta.data$nFeature_RNA), log10(singlet_24h_list[[1]]@meta.data$nCount_RNA))+
  geom_point(color = 'steelblue')+
  theme_classic()
```

## PD1
```{r, warning = F, message = F}
singlet_24h_list[[2]]
singlet_24h_list[[2]][["percent.mt"]] <- PercentageFeatureSet(singlet_24h_list[[2]], pattern = "^MT-", assay = 'RNA')
VlnPlot(singlet_24h_list[[2]], features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, log = T, pt.size = .5)
VlnPlot(singlet_24h_list[[2]], features = c("nFeature_Antibody.capture", "nCount_Antibody.capture"), ncol = 2, log = T, pt.size = .5, assay = 'Antibody.capture')
qplot(log10(singlet_24h_list[[2]]@meta.data$nCount_RNA), singlet_24h_list[[2]]@meta.data$percent.mt)+
  geom_point(color = 'steelblue')+
  theme_classic()
qplot(log10(singlet_24h_list[[2]]@meta.data$nFeature_RNA), singlet_24h_list[[2]]@meta.data$percent.mt)+
  geom_point(color = 'steelblue')+
  theme_classic()
qplot(log10(singlet_24h_list[[2]]@meta.data$nFeature_RNA), log10(singlet_24h_list[[2]]@meta.data$nCount_RNA))+
  geom_point(color = 'steelblue')+
  theme_classic()
```

## condition_2
```{r, warning = F, message = F}
singlet_24h_list[[3]]
singlet_24h_list[[3]][["percent.mt"]] <- PercentageFeatureSet(singlet_24h_list[[3]], pattern = "^MT-", assay = 'RNA')
VlnPlot(singlet_24h_list[[3]], features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, log = T, pt.size = .5)
VlnPlot(singlet_24h_list[[3]], features = c("nFeature_Antibody.capture", "nCount_Antibody.capture"), ncol = 2, log = T, pt.size = .5, assay = 'Antibody.capture')
qplot(log10(singlet_24h_list[[3]]@meta.data$nCount_RNA), singlet_24h_list[[3]]@meta.data$percent.mt)+
  geom_point(color = 'steelblue')+
  theme_classic()
qplot(log10(singlet_24h_list[[3]]@meta.data$nFeature_RNA), singlet_24h_list[[3]]@meta.data$percent.mt)+
  geom_point(color = 'steelblue')+
  theme_classic()
qplot(log10(singlet_24h_list[[3]]@meta.data$nFeature_RNA), log10(singlet_24h_list[[3]]@meta.data$nCount_RNA))+
  geom_point(color = 'steelblue')+
  theme_classic()
```

## PBMC-1
```{r, warning = F, message = F}
singlet_24h_list[[4]]
singlet_24h_list[[4]][["percent.mt"]] <- PercentageFeatureSet(singlet_24h_list[[4]], pattern = "^MT-", assay = 'RNA')
VlnPlot(singlet_24h_list[[4]], features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, log = T, pt.size = .5)
VlnPlot(singlet_24h_list[[4]], features = c("nFeature_Antibody.capture", "nCount_Antibody.capture"), ncol = 2, log = T, pt.size = .5, assay = 'Antibody.capture')
qplot(log10(singlet_24h_list[[4]]@meta.data$nCount_RNA), singlet_24h_list[[4]]@meta.data$percent.mt)+
  geom_point(color = 'steelblue')+
  theme_classic()
qplot(log10(singlet_24h_list[[4]]@meta.data$nFeature_RNA), singlet_24h_list[[4]]@meta.data$percent.mt)+
  geom_point(color = 'steelblue')+
  theme_classic()
qplot(log10(singlet_24h_list[[4]]@meta.data$nFeature_RNA), log10(singlet_24h_list[[4]]@meta.data$nCount_RNA))+
  geom_point(color = 'steelblue')+
  theme_classic()
```

## condition_3
```{r, warning = F, message = F}
singlet_24h_list[[5]]
singlet_24h_list[[5]][["percent.mt"]] <- PercentageFeatureSet(singlet_24h_list[[5]], pattern = "^MT-", assay = 'RNA')
VlnPlot(singlet_24h_list[[5]], features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, log = T, pt.size = .5)
VlnPlot(singlet_24h_list[[5]], features = c("nFeature_Antibody.capture", "nCount_Antibody.capture"), ncol = 2, log = T, pt.size = .5, assay = 'Antibody.capture')
qplot(log10(singlet_24h_list[[5]]@meta.data$nCount_RNA), singlet_24h_list[[5]]@meta.data$percent.mt)+
  geom_point(color = 'steelblue')+
  theme_classic()
qplot(log10(singlet_24h_list[[5]]@meta.data$nFeature_RNA), singlet_24h_list[[5]]@meta.data$percent.mt)+
  geom_point(color = 'steelblue')+
  theme_classic()
qplot(log10(singlet_24h_list[[5]]@meta.data$nFeature_RNA), log10(singlet_24h_list[[5]]@meta.data$nCount_RNA))+
  geom_point(color = 'steelblue')+
  theme_classic()
```

## condition_4
```{r, warning = F, message = F}
singlet_24h_list[[6]]
singlet_24h_list[[6]][["percent.mt"]] <- PercentageFeatureSet(singlet_24h_list[[6]], pattern = "^MT-", assay = 'RNA')
VlnPlot(singlet_24h_list[[6]], features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, log = T, pt.size = .5)
VlnPlot(singlet_24h_list[[6]], features = c("nFeature_Antibody.capture", "nCount_Antibody.capture"), ncol = 2, log = T, pt.size = .5, assay = 'Antibody.capture')
qplot(log10(singlet_24h_list[[6]]@meta.data$nCount_RNA), singlet_24h_list[[6]]@meta.data$percent.mt)+
  geom_point(color = 'steelblue')+
  theme_classic()
qplot(log10(singlet_24h_list[[6]]@meta.data$nFeature_RNA), singlet_24h_list[[6]]@meta.data$percent.mt)+
  geom_point(color = 'steelblue')+
  theme_classic()
qplot(log10(singlet_24h_list[[6]]@meta.data$nFeature_RNA), log10(singlet_24h_list[[6]]@meta.data$nCount_RNA))+
  geom_point(color = 'steelblue')+
  theme_classic()
```

## condition_5
```{r, warning = F, message = F}
singlet_24h_list[[7]]
singlet_24h_list[[7]][["percent.mt"]] <- PercentageFeatureSet(singlet_24h_list[[7]], pattern = "^MT-", assay = 'RNA')
VlnPlot(singlet_24h_list[[7]], features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, log = T, pt.size = .5)
VlnPlot(singlet_24h_list[[7]], features = c("nFeature_Antibody.capture", "nCount_Antibody.capture"), ncol = 2, log = T, pt.size = .5, assay = 'Antibody.capture')
qplot(log10(singlet_24h_list[[7]]@meta.data$nCount_RNA), singlet_24h_list[[7]]@meta.data$percent.mt)+
  geom_point(color = 'steelblue')+
  theme_classic()
qplot(log10(singlet_24h_list[[7]]@meta.data$nFeature_RNA), singlet_24h_list[[7]]@meta.data$percent.mt)+
  geom_point(color = 'steelblue')+
  theme_classic()
qplot(log10(singlet_24h_list[[7]]@meta.data$nFeature_RNA), log10(singlet_24h_list[[7]]@meta.data$nCount_RNA))+
  geom_point(color = 'steelblue')+
  theme_classic()
```

## condition_6
```{r, warning = F, message = F}
singlet_24h_list[[8]]
singlet_24h_list[[8]][["percent.mt"]] <- PercentageFeatureSet(singlet_24h_list[[8]], pattern = "^MT-", assay = 'RNA')
VlnPlot(singlet_24h_list[[8]], features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, log = T, pt.size = .5)
VlnPlot(singlet_24h_list[[8]], features = c("nFeature_Antibody.capture", "nCount_Antibody.capture"), ncol = 2, log = T, pt.size = .5, assay = 'Antibody.capture')
qplot(log10(singlet_24h_list[[8]]@meta.data$nCount_RNA), singlet_24h_list[[8]]@meta.data$percent.mt)+
  geom_point(color = 'steelblue')+
  theme_classic()
qplot(log10(singlet_24h_list[[8]]@meta.data$nFeature_RNA), singlet_24h_list[[8]]@meta.data$percent.mt)+
  geom_point(color = 'steelblue')+
  theme_classic()
qplot(log10(singlet_24h_list[[8]]@meta.data$nFeature_RNA), log10(singlet_24h_list[[8]]@meta.data$nCount_RNA))+
  geom_point(color = 'steelblue')+
  theme_classic()
```

## CTLA4
```{r, warning = F, message = F}
singlet_24h_list[[9]]
singlet_24h_list[[9]][["percent.mt"]] <- PercentageFeatureSet(singlet_24h_list[[9]], pattern = "^MT-", assay = 'RNA')
VlnPlot(singlet_24h_list[[9]], features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, log = T, pt.size = .5)
VlnPlot(singlet_24h_list[[9]], features = c("nFeature_Antibody.capture", "nCount_Antibody.capture"), ncol = 2, log = T, pt.size = .5, assay = 'Antibody.capture')
qplot(log10(singlet_24h_list[[9]]@meta.data$nCount_RNA), singlet_24h_list[[9]]@meta.data$percent.mt)+
  geom_point(color = 'steelblue')+
  theme_classic()
qplot(log10(singlet_24h_list[[9]]@meta.data$nFeature_RNA), singlet_24h_list[[9]]@meta.data$percent.mt)+
  geom_point(color = 'steelblue')+
  theme_classic()
qplot(log10(singlet_24h_list[[9]]@meta.data$nFeature_RNA), log10(singlet_24h_list[[9]]@meta.data$nCount_RNA))+
  geom_point(color = 'steelblue')+
  theme_classic()
```

## condition_7
```{r, warning = F, message = F}
singlet_24h_list[[10]]
singlet_24h_list[[10]][["percent.mt"]] <- PercentageFeatureSet(singlet_24h_list[[10]], pattern = "^MT-", assay = 'RNA')
VlnPlot(singlet_24h_list[[10]], features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, log = T, pt.size = .5)
VlnPlot(singlet_24h_list[[10]], features = c("nFeature_Antibody.capture", "nCount_Antibody.capture"), ncol = 2, log = T, pt.size = .5, assay = 'Antibody.capture')
qplot(log10(singlet_24h_list[[10]]@meta.data$nCount_RNA), singlet_24h_list[[10]]@meta.data$percent.mt)+
  geom_point(color = 'steelblue')+
  theme_classic()
qplot(log10(singlet_24h_list[[10]]@meta.data$nFeature_RNA), singlet_24h_list[[10]]@meta.data$percent.mt)+
  geom_point(color = 'steelblue')+
  theme_classic()
qplot(log10(singlet_24h_list[[10]]@meta.data$nFeature_RNA), log10(singlet_24h_list[[10]]@meta.data$nCount_RNA))+
  geom_point(color = 'steelblue')+
  theme_classic()
```

# Filter

```{r}
singlet_24h <- subset(singlet_24h, subset = nFeature_RNA > 500 & percent.mt < 10)

ggplot(singlet_24h@meta.data, aes(x = sample_id, y = log10(nFeature_RNA), fill = sample_id))+
  geom_violin()+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 315, hjust = 0))

ggplot(singlet_24h@meta.data, aes(x = sample_id, y = log10(nCount_RNA), fill = sample_id))+
  geom_violin()+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 315, hjust = 0))

ggplot(singlet_24h@meta.data, aes(x = sample_id, y = log10(percent.mt), fill = sample_id))+
  geom_violin()+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 315, hjust = 0))
          
```

```{r, eval = F}
saveRDS(singlet_24h, file = 'singlet_24h_filtered.rds')
```