---
title: "Plaque_vs_control"
author: "Michael Gildea"
date: "2024-03-13"
output:
  html_document:
    code_folding: hide
    toc: yes
    theme: spacelab
---


```{r}
time <- Sys.time()
print(paste('This notebook was knit on:', time))
print(version)
```


```{r, message=F, warning=F}
library(viridis)
library(Seurat)
library(ggplot2)
library(CVRCFunc)
library(SingleR)
library(reshape2)
library(stringr)
```

```{r}
integrated_dedup <- readRDS(file = 'integrated_dedup.rds')
integrated_dedup$location <- integrated_dedup$Pathology
integrated_dedup$location[which(integrated_dedup$location == 'FC' | integrated_dedup$location == 'FA')] <- 'Plaque'
ICI_targets <-read.csv('../ICI_target_pairs_refined.csv', header = T)
ICI_targets_all <- unique(c(ICI_targets$Receptors, ICI_targets$Ligand))
```

## find markers wilcox all
```{r}
Idents(integrated_dedup) <- 'annotation_fine'
#diabetes
sig_up <- vector()
sig_down <- vector()
for(i in unique(integrated_dedup$annotation_fine)){
  tr <- tryCatch(markers <- Seurat::FindMarkers(integrated_dedup, ident.1 = 'Plaque', ident.2 = 'AIT', group.by = 'location', subset.ident = i, assay = 'RNA', slot = 'data'),
  error = function(e) e) 
  if(inherits(tr, "error")){
    markers <- data.frame(row.names = ICI_targets_all, 
                          p_val = rep(1, length(ICI_targets_all)),
                          avg_log2FC = rep(0, length(ICI_targets_all)),
                          pct.1 = rep(0, length(ICI_targets_all)),
                          pct.2 = rep(1, length(ICI_targets_all)),
                          p_val_adj = rep(1, length(ICI_targets_all)))
  }
  write.csv(markers, file = paste('annotation_fine_wilcox_location/',i,'.csv',sep = ''), quote = F)
  sig_up <- c(sig_up, length(which(markers$p_val_adj < 0.1 & markers$avg_log2FC > 0)))
  sig_down <- c(sig_down, length(which(markers$p_val_adj < 0.1 & markers$avg_log2FC < 0)))
}
summary_results <- data.frame(cluster = unique(integrated_dedup$annotation_fine), sig_up = sig_up, sig_down = sig_down, sig_all = sig_up+sig_down)
write.csv(file = paste('annotation_fine_wilcox_location/summary_results.csv'), summary_results, quote = F, row.names = F)
```

## Wilcox Sex AIT
```{r}
sex <- as.vector(integrated_dedup$Sample)
sex[which(sex == 'LAD_scRNAseq_1')] <- 'Female'
sex[which(sex != 'Female')] <- 'Male'
integrated_dedup$sex <- sex

Idents(integrated_dedup) <- 'location'
integrated_dedup_AIT <- subset(integrated_dedup, idents = 'AIT') 
Idents(integrated_dedup_AIT) <- 'annotation_fine'

sig_up <- vector()
sig_down <- vector()
for(i in unique(integrated_dedup_AIT$annotation_fine)){
  tr <- tryCatch(markers <- Seurat::FindMarkers(integrated_dedup_AIT, ident.1 = 'Female', ident.2 = 'Male', group.by = 'sex', subset.ident = i, assay = 'RNA', slot = 'data'),
  error = function(e) e) 
  if(inherits(tr, "error")){
    markers <- data.frame(row.names = ICI_targets_all, 
                          p_val = rep(1, length(ICI_targets_all)),
                          avg_log2FC = rep(0, length(ICI_targets_all)),
                          pct.1 = rep(0, length(ICI_targets_all)),
                          pct.2 = rep(1, length(ICI_targets_all)),
                          p_val_adj = rep(1, length(ICI_targets_all)))
  }
  write.csv(markers, file = paste('annotation_fine_wilcox_sex_AIT/',i,'.csv',sep = ''), quote = F)
  sig_up <- c(sig_up, length(which(markers$p_val_adj < 0.1 & markers$avg_log2FC > 0)))
  sig_down <- c(sig_down, length(which(markers$p_val_adj < 0.1 & markers$avg_log2FC < 0)))
}
summary_results <- data.frame(cluster = unique(integrated_dedup_AIT$annotation_fine), sig_up = sig_up, sig_down = sig_down, sig_all = sig_up+sig_down)
write.csv(file = paste('annotation_fine_wilcox_sex_AIT/summary_results.csv'), summary_results, quote = F, row.names = F)
```