---
title: "Myeloid_wnn_subcluster"
author: "Michael Gildea"
date: "7/21/2023"
output:
  html_document:
    code_folding: hide
    toc: yes
    theme: spacelab
---


```{r, message=F, warning=F}
library(Seurat)
library(ggplot2)
library(reticulate)
library(CVRCFunc)
library(SeuratDisk)
library(pheatmap)
library(dplyr)
library(kableExtra)
library(scater)
library(patchwork)
library(viridis)
use_miniconda(condaenv = "/gpfs/data/fisherlab/conda_envs/scVelo")
print('This notebook was generated on: ')
print(Sys.time())
#integrated_wnn <- readRDS(file = '/gpfs/data/giannarellilab/Mike_G/Immune_checkpoint_inhibitors/PBMC_ICI_CITEseq/CTLA4_PD1_treated/integrated_wnn_majoranno.rds')
```

# Extract Myeloid
```{r, eval = F}
Idents(integrated_wnn) <- 'annotation_major'
Myeloid <- subset(integrated_wnn, idents = 'Myeloid')
```

```{r}
load(file = 'Myeloid_workspace.RData')
```

# Sub cluster using RNA and protein data with WNN
```{r, eval = F}
Idents(Myeloid) <- 'orig.ident'
Myeloid_4h <- subset(Myeloid, idents = '4h')
Myeloid_4h <- SCTransform(Myeloid_4h,  vst.flavor = "v2", return.only.var.genes = F)
Myeloid_24h <- subset(Myeloid, idents = '24h')
Myeloid_24h <- SCTransform(Myeloid_24h,  vst.flavor = "v2", return.only.var.genes = F)
Myeloid_list <- list(hour_4 = Myeloid_4h, hour_24 = Myeloid_24h)
features <- SelectIntegrationFeatures(object.list = Myeloid_list, nfeatures = 3000)
rm(Myeloid_24h, Myeloid_4h, Myeloid_list)
Myeloid <- RunPCA(Myeloid, features = features, assay = 'integrated', reduction.name = 'pca')
ElbowPlot(Myeloid, reduction = 'pca')
Myeloid <- FindMultiModalNeighbors(Myeloid, reduction.list = list("pca", "pca.adt"),  dims.list = list(1:15, 1:10), modality.weight.name = "RNA.weight")
Myeloid <- RunUMAP(Myeloid, nn.name = "weighted.nn", reduction.name = "wnn.umap", reduction.key = "wnnUMAP_")
Myeloid <- FindClusters(Myeloid, graph.name = "wsnn", algorithm = 4, verbose = FALSE, resolution = 1)
Myeloid <- NormalizeData(Myeloid, assay = 'RNA')
s.genes <- cc.genes$s.genes
g2m.genes <- cc.genes$g2m.genes
DefaultAssay(Myeloid) <- 'RNA'
Myeloid <- CellCycleScoring(Myeloid, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)
saveRDS(Myeloid, file = 'Myeloid.rds')
save.image('Myeloid_workspace.RData')
```


# Find cluster markers 
```{r, eval = F}
FindMarkersBulk(seurat = Myeloid, clus_ident = 'annotation_fine', sample_ident = 'sample_id', out_dir = 'dea_results_myeloid/FindMarkersBulk_outs_myeloid_annotated_ADT', assay = 'ADT')
FindMarkersBulk(seurat = Myeloid, clus_ident = 'annotation_fine', sample_ident = 'sample_id', out_dir = 'dea_results_myeloid/FindMarkersBulk_outs_myeloid_annotated_RNA', assay = 'RNA')
```

# FindAllmarkers for individual samples
```{r}
Idents(Myeloid) <- 'sample_id'
myeloid_sub <- subset(Myeloid, idents = 'CTLA4-4h')
Idents(myeloid_sub) <- 'annotation_fine'
markers <- FindAllMarkers(myeloid_sub, assay = 'RNA', slot = 'data')
for(i in unique(markers$cluster)){
  marker_sub <- markers[which(markers$cluster == i),]
  write.csv(marker_sub, file = paste('dea_results_myeloid/FindAllMarkers/CTLA4_4h/',i,'.csv', sep = ''))
}

myeloid_sub <- subset(Myeloid, idents = 'CTLA4-24h')
Idents(myeloid_sub) <- 'annotation_fine'
markers <- FindAllMarkers(myeloid_sub, assay = 'RNA', slot = 'data')
for(i in unique(markers$cluster)){
  marker_sub <- markers[which(markers$cluster == i),]
  write.csv(marker_sub, file = paste('dea_results_myeloid/FindAllMarkers/CTLA4_24h/',i,'.csv', sep = ''))
}

myeloid_sub <- subset(Myeloid, idents = 'PD1-4h')
Idents(myeloid_sub) <- 'annotation_fine'
markers <- FindAllMarkers(myeloid_sub, assay = 'RNA', slot = 'data')
for(i in unique(markers$cluster)){
  marker_sub <- markers[which(markers$cluster == i),]
  write.csv(marker_sub, file = paste('dea_results_myeloid/FindAllMarkers/PD1_4h/',i,'.csv', sep = ''))
}

myeloid_sub <- subset(Myeloid, idents = 'PD1-24h')
Idents(myeloid_sub) <- 'annotation_fine'
markers <- FindAllMarkers(myeloid_sub, assay = 'RNA', slot = 'data')
for(i in unique(markers$cluster)){
  marker_sub <- markers[which(markers$cluster == i),]
  write.csv(marker_sub, file = paste('dea_results_myeloid/FindAllMarkers/PD1_24h/',i,'.csv', sep = ''))
}
```
